server:
  port: 8888

github:
  client:
    id: "07321f78eebe9dfe4011"
    secret: "01fff5af82bb4f688ce20138c5c0eee0a1713da8"
  redirect_uri: "http://localhost:8888/callback"

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/community"
    username: "root"
    password: "root"
    driver-class-name: "com.mysql.jdbc.Driver"

mybatis:
#  config-location: classpath:mybatis/mapper/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
